# Generated by Django 5.2.10 on 2026-03-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'En Linea'), ('OFFLINE', 'Fuera de Linea'), ('MAINTENANCE', 'Mantenimiento')], db_index=True, default='ONLINE', max_length=20)),
                ('resolution', models.CharField(default='1080p', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameramanGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='e.g., Chaleco, Radio, Batería', max_length=100)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('assigned_to_name', models.CharField(blank=True, help_text='Nombre libre (legado)', max_length=100)),
                ('condition', models.CharField(choices=[('NEW', 'Nuevo'), ('GOOD', 'Bueno'), ('FAIR', 'Regular'), ('POOR', 'Malo'), ('BROKEN', 'Roto')], default='GOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='e.g., SITE-01-NVR', max_length=100, unique=True)),
                ('system_type', models.CharField(choices=[('NVR', 'NVR (Grabador)'), ('CCTV', 'Sistema CCTV Completo')], default='CCTV', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, help_text='e.g., AEP, EZE', max_length=10, unique=True)),
                ('airport', models.CharField(blank=True, help_text='Aeropuerto', max_length=100, null=True)),
                ('province', models.CharField(blank=True, help_text='Provincia', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud', max_digits=9, null=True)),
                ('map_enabled', models.BooleanField(db_index=True, default=False, help_text='Mostrar en mapa operacional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
