# Generated by Django 5.2 on 2026-04-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramangear',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gear', to='personnel.person'),
        ),
        migrations.AddField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='assets.server'),
        ),
        migrations.AddField(
            model_name='server',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='assets.system'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Entidad Superior (e.g., CREV)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='assets.unit'),
        ),
        migrations.AddField(
            model_name='system',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='assets.unit'),
        ),
    ]
