# Generated by Django 5.2.11 on 2026-03-06 18:20
# Rewritten to use SeparateDatabaseAndState: all columns already existed in the DB
# (server_id on camera, assigned_to_name on cameramangear, geo fields on unit).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_camera_name_alter_camera_status_and_more'),
        ('personnel', '0009_alter_person_role'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='camera',
                    name='server',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='assets.server'),
                ),
                migrations.AddField(
                    model_name='cameramangear',
                    name='assigned_to_name',
                    field=models.CharField(blank=True, help_text='Nombre libre (legado)', max_length=100),
                ),
                migrations.AddField(
                    model_name='unit',
                    name='latitude',
                    field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud', max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='unit',
                    name='longitude',
                    field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud', max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='unit',
                    name='map_enabled',
                    field=models.BooleanField(db_index=True, default=False, help_text='Mostrar en mapa operacional'),
                ),
                migrations.AddField(
                    model_name='unit',
                    name='province',
                    field=models.CharField(blank=True, help_text='Provincia', max_length=100, null=True),
                ),
                migrations.AlterField(
                    model_name='cameramangear',
                    name='assigned_to',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gear', to='personnel.person'),
                ),
            ],
        ),
    ]
