# Generated by Django 5.2 on 2026-03-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_camera_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='photo_data',
            field=models.TextField(blank=True, default='', help_text='Imagen de referencia pequena en formato data URL base64.'),
        ),
    ]
