# Generated by Django 5.2 on 2026-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_camera_photo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='report_authenticity_detail_default',
        ),
        migrations.RemoveField(
            model_name='system',
            name='report_authenticity_mode_default',
        ),
        migrations.RemoveField(
            model_name='system',
            name='report_hash_program_default',
        ),
        migrations.RemoveField(
            model_name='system',
            name='report_native_hash_algorithm_other_default',
        ),
        migrations.RemoveField(
            model_name='system',
            name='report_native_hash_algorithms_default',
        ),
        migrations.AddField(
            model_name='system',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Cantidad de tiempo de resguardo (dias)'),
        ),
    ]
