# Generated by Django 5.2 on 2026-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_system_report_authenticity_detail_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='vms_version',
            field=models.CharField(blank=True, default='', help_text='Version del software VMS', max_length=50),
        ),
    ]
