# Generated by Django 5.2 on 2026-03-16 13:57

from django.db import migrations, models


def normalize_conditions(apps, schema_editor):
    CameramanGear = apps.get_model('assets', 'CameramanGear')
    CameramanGear.objects.filter(condition='NEW').update(condition='GOOD')
    CameramanGear.objects.filter(condition='POOR').update(condition='FAIR')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_system_vms_version'),
    ]

    operations = [
        migrations.RunPython(normalize_conditions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cameramangear',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Bueno'), ('FAIR', 'Regular'), ('BROKEN', 'Roto')], default='GOOD', max_length=20),
        ),
    ]
