# Generated by Django 5.2.10 on 2026-03-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('ollama', 'Ollama')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(choices=[('improve_text', 'Mejora de texto'), ('video_report', 'Generación de informe')], default='improve_text', max_length=30)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de uso de IA',
                'verbose_name_plural': 'Registros de uso de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_number', models.CharField(blank=True, help_text='Número de asunto administrativo', max_length=50, null=True, verbose_name='Nro Asunto')),
                ('order_number', models.IntegerField(blank=True, help_text='Número de orden secuencial', null=True, verbose_name='Nº Orden')),
                ('entry_date', models.DateField(blank=True, help_text='Fecha de ingreso de la solicitud', null=True, verbose_name='Fecha Ingreso')),
                ('request_type', models.CharField(blank=True, choices=[('OFICIO', 'Oficio'), ('NOTA', 'Nota'), ('EXHORTO', 'Exhorto'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo Solicitud')),
                ('request_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Solicitud')),
                ('requester', models.CharField(blank=True, help_text='Juzgado, Fiscalía u organismo solicitante', max_length=200, null=True, verbose_name='Solicitante')),
                ('judicial_case_number', models.CharField(blank=True, db_index=True, help_text='Número de causa o prevención sumaria', max_length=100, null=True, verbose_name='Nº Causa Judicial')),
                ('case_title', models.TextField(blank=True, help_text='Carátula de la causa', null=True, verbose_name='Carátula')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Hecho')),
                ('crime_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Delito')),
                ('intervening_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependencia Interviniente')),
                ('start_time', models.DateTimeField(verbose_name='Hora Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora Fin')),
                ('record_type', models.CharField(choices=[('VD', 'VD - Video'), ('IM', 'Imagen'), ('OT', 'Otro')], default='VD', max_length=2, verbose_name='Tipo de Registro')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('has_backup', models.BooleanField(default=False, verbose_name='¿Tiene Backup?')),
                ('backup_path', models.CharField(blank=True, help_text='Ubicación física o lógica del backup', max_length=500, null=True, verbose_name='Ruta del Backup')),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='Hash para verificación de integridad', max_length=128, null=True, verbose_name='Hash del Archivo')),
                ('hash_algorithm', models.CharField(blank=True, choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3', 'SHA-3'), ('sha1', 'SHA-1')], help_text='Algoritmo utilizado para calcular el hash', max_length=10, null=True, verbose_name='Algoritmo de Hash')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño en bytes', null=True, verbose_name='Tamaño del Archivo')),
                ('is_integrity_verified', models.BooleanField(default=False, help_text='Verificación técnica automática del hash', verbose_name='¿Integridad Verificada?')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación CREV')),
                ('is_editable', models.BooleanField(default=True, help_text='False si ya fue verificado por CREV', verbose_name='¿Es Editable?')),
                ('delivery_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('DERIVADO', 'Derivado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Entrega')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='assets.camera', verbose_name='Cámara')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_records', to='personnel.person', verbose_name='Operador')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_records', to='personnel.person', verbose_name='Recepcionado por')),
                ('verified_by_crev', models.ForeignKey(blank=True, help_text='Fiscalizador CREV que certificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_records', to='personnel.person', verbose_name='Verificado por CREV')),
            ],
            options={
                'verbose_name': 'Registro Fílmico',
                'verbose_name_plural': 'Registros Fílmicos',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('records', models.ManyToManyField(related_name='catalogs', to='records.filmrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('form_data', models.JSONField(default=dict)),
                ('film_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informe', to='records.filmrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['judicial_case_number'], name='records_fil_judicia_de6410_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['issue_number'], name='records_fil_issue_n_b8c176_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['entry_date'], name='records_fil_entry_d_7158a8_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['delivery_status'], name='records_fil_deliver_b761fe_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['file_hash'], name='records_fil_file_ha_bb8ee6_idx'),
        ),
    ]
