# Generated by Django 5.2 on 2026-04-08 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('ollama', 'Ollama')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(choices=[('improve_text', 'Mejora de texto'), ('video_report', 'Generación de informe')], default='improve_text', max_length=30)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de uso de IA',
                'verbose_name_plural': 'Registros de uso de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro Asunto')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Nº Orden')),
                ('entry_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Fecha Ingreso')),
                ('request_type', models.CharField(blank=True, choices=[('FORMULARIO', 'Formulario'), ('MEMORANDO', 'Memorando'), ('NOTA', 'Nota'), ('OFICIO', 'Oficio'), ('EXHORTO', 'Exhorto'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo Solicitud')),
                ('request_kind', models.CharField(blank=True, choices=[('DENUNCIA', 'Denuncia'), ('PROCEDIMIENTO', 'Procedimiento'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo Requerimiento')),
                ('request_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Solicitud')),
                ('requester', models.CharField(blank=True, max_length=200, null=True, verbose_name='Solicitante')),
                ('judicial_case_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nº Causa Judicial / Prevención Sumaria')),
                ('case_title', models.TextField(blank=True, null=True, verbose_name='Carátula')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Hecho')),
                ('incident_time', models.TimeField(blank=True, null=True, verbose_name='Hora del Hecho')),
                ('incident_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar del Hecho')),
                ('incident_sector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector del Hecho')),
                ('crime_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Delito')),
                ('criminal_problematic', models.CharField(blank=True, max_length=250, null=True, verbose_name='Problematica Delictiva')),
                ('incident_modality', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modalidad del Hecho')),
                ('intervening_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependencia Interviniente')),
                ('judicial_office', models.CharField(blank=True, max_length=250, null=True, verbose_name='Juzgado / Fiscalia')),
                ('judicial_secretary', models.CharField(blank=True, max_length=250, null=True, verbose_name='Secretaria')),
                ('judicial_holder', models.CharField(blank=True, max_length=250, null=True, verbose_name='Titular')),
                ('sistema', models.CharField(blank=True, help_text='Sistema o dispositivo del que proviene el material (ej: MILESTONE, VIPRO, DAHUA, NVR HIKVISION)', max_length=200, null=True, verbose_name='Sistema CCTV / VMS')),
                ('operator', models.CharField(blank=True, help_text='Jerarquía, Nombre y Apellido del responsable', max_length=200, null=True, verbose_name='Confeccionado por')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('dvd_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de DVD')),
                ('report_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Informe')),
                ('ifgra_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='IFGRA')),
                ('expediente_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Expediente')),
                ('delivery_act_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Acta Entrega / Elevación')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('retrieved_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Retirado por')),
                ('organism', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organismo')),
                ('delivery_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('DERIVADO', 'Derivado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('has_backup', models.BooleanField(default=False, verbose_name='¿Tiene Backup?')),
                ('backup_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Backup')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Hash del Archivo')),
                ('hash_algorithm', models.CharField(blank=True, choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3', 'SHA-3'), ('sha1', 'SHA-1')], max_length=10, null=True, verbose_name='Algoritmo de Hash')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('is_integrity_verified', models.BooleanField(default=False, verbose_name='¿Integridad Verificada?')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación CREV')),
                ('is_editable', models.BooleanField(default=True, verbose_name='¿Es Editable?')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('generator_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_film_records', to='assets.unit', verbose_name='Unidad Generador')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_records', to='personnel.person', verbose_name='Recepcionado por')),
                ('verified_by_crev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_records', to='personnel.person', verbose_name='Verificado por CREV')),
            ],
            options={
                'verbose_name': 'Registro Fílmico',
                'verbose_name_plural': 'Registros Fílmicos',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('records', models.ManyToManyField(related_name='catalogs', to='records.filmrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilmRecordInvolvedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('DAMNIFICADO', 'Damnificado'), ('DENUNCIANTE', 'Denunciante'), ('DETENIDO', 'Detenido'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('document_type', models.CharField(blank=True, max_length=30, null=True)),
                ('document_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('film_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_people', to='records.filmrecord')),
            ],
            options={
                'verbose_name': 'Persona Involucrada',
                'verbose_name_plural': 'Personas Involucradas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('form_data', models.JSONField(default=dict)),
                ('film_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informe', to='records.filmrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['judicial_case_number'], name='records_fil_judicia_de6410_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['issue_number'], name='records_fil_issue_n_b8c176_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['entry_date'], name='records_fil_entry_d_7158a8_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['delivery_status'], name='records_fil_deliver_b761fe_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['file_hash'], name='records_fil_file_ha_bb8ee6_idx'),
        ),
    ]
