# Generated by Django 5.2.11 on 2026-03-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('form_data', models.JSONField(default=dict)),
                ('film_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informe', to='records.filmrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
