# Generated by Django 5.2.11 on 2026-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_videoanalysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmrecord',
            name='hash_algorithm',
            field=models.CharField(blank=True, choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3', 'SHA-3'), ('sha1', 'SHA-1')], help_text='Algoritmo utilizado para calcular el hash', max_length=10, null=True, verbose_name='Algoritmo de Hash'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('ollama', 'Ollama')], max_length=30),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash para verificación de integridad', max_length=128, null=True, verbose_name='Hash del Archivo'),
        ),
    ]
