# Generated by Django 5.2.11 on 2026-03-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_camera_server_cameramangear_assigned_to_name_and_more'),
        ('personnel', '0010_alter_person_guard_group_alter_person_rank_and_more'),
        ('records', '0006_alter_catalog_name_alter_filmrecord_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmrecord',
            name='record_type',
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='delivery_act_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Acta Entrega / Elevación'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='dvd_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de DVD'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='expediente_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='ifgra_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IFGRA'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='organism',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organismo'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='report_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Informe'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='retrieved_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Retirado por'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='backup_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Backup'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='assets.camera', verbose_name='Cámara'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='case_title',
            field=models.TextField(blank=True, null=True, verbose_name='Carátula'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='delivery_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('DERIVADO', 'Derivado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Hash del Archivo'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='hash_algorithm',
            field=models.CharField(blank=True, choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3', 'SHA-3'), ('sha1', 'SHA-1')], max_length=10, null=True, verbose_name='Algoritmo de Hash'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='¿Es Editable?'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='is_integrity_verified',
            field=models.BooleanField(default=False, verbose_name='¿Integridad Verificada?'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='issue_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro Asunto'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='judicial_case_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nº Causa Judicial / Prevención Sumaria'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_records', to='personnel.person', verbose_name='Confeccionado por'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Orden'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='request_type',
            field=models.CharField(blank=True, choices=[('FORMULARIO', 'Formulario'), ('MEMORANDO', 'Memorando'), ('NOTA', 'Nota'), ('OFICIO', 'Oficio'), ('EXHORTO', 'Exhorto'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo Solicitud'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='requester',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='verified_by_crev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_records', to='personnel.person', verbose_name='Verificado por CREV'),
        ),
    ]
