# Generated by Django 5.2.11 on 2026-03-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_filmrecord_record_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmrecord',
            name='camera',
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='sistema',
            field=models.CharField(blank=True, help_text='Sistema o dispositivo del que proviene el material (ej: MILESTONE, VIPRO, DAHUA, NVR HIKVISION)', max_length=200, null=True, verbose_name='Sistema CCTV / VMS'),
        ),
    ]
