# Generated by Django 5.2.12 on 2026-03-09 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_camera_server_cameramangear_assigned_to_name_and_more'),
        ('records', '0008_remove_filmrecord_camera_filmrecord_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmrecord',
            name='criminal_problematic',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Problematica Delictiva'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='generator_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_film_records', to='assets.unit', verbose_name='Unidad Generador'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='incident_modality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Modalidad del Hecho'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='incident_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar del Hecho'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='incident_sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector del Hecho'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='incident_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del Hecho'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='judicial_holder',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='judicial_office',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Juzgado / Fiscalia'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='judicial_secretary',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Secretaria'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='request_kind',
            field=models.CharField(blank=True, choices=[('DENUNCIA', 'Denuncia'), ('PROCEDIMIENTO', 'Procedimiento')], max_length=20, null=True, verbose_name='Tipo Requerimiento'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.CreateModel(
            name='FilmRecordInvolvedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('DAMNIFICADO', 'Damnificado'), ('DENUNCIANTE', 'Denunciante'), ('DETENIDO', 'Detenido'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('document_type', models.CharField(blank=True, max_length=30, null=True)),
                ('document_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('film_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_people', to='records.filmrecord')),
            ],
            options={
                'verbose_name': 'Persona Involucrada',
                'verbose_name_plural': 'Personas Involucradas',
                'ordering': ['id'],
            },
        ),
    ]
