# Generated by Django 5.2.12 on 2026-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_filmrecord_criminal_problematic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrecord',
            name='request_kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DENUNCIA', 'Denuncia'),
                    ('PROCEDIMIENTO', 'Procedimiento'),
                    ('OTRO', 'Otro'),
                ],
                max_length=20,
                null=True,
                verbose_name='Tipo Requerimiento',
            ),
        ),
    ]
