# Generated by Django 5.2.12 on 2026-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_filmrecord_request_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrecord',
            name='operator',
            field=models.CharField(blank=True, help_text='Jerarquía, Nombre y Apellido del responsable', max_length=200, null=True, verbose_name='Confeccionado por'),
        ),
    ]
