# Generated by Django 5.2 on 2026-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_videoanalysisreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filmrecordinvolvedperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videoanalysisreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
