"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url as _dj_db_url
from datetime import timedelta
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file():
    """Load key=value pairs from backend/.env into process env."""
    env_candidates = [
        BASE_DIR.parent / '.env',  # backend/.env (recommended)
        BASE_DIR / '.env',         # backend/src/.env (legacy)
    ]

    for env_path in env_candidates:
        if not env_path.exists():
            continue

        try:
            lines = env_path.read_text(encoding='utf-8-sig').splitlines()
        except OSError:
            return

        for raw_line in lines:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue

            if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
                value = value[1:-1]

            os.environ.setdefault(key, value)
        return


_load_local_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-#nhi6=ie9_%of*^vqv23mkddp^d9!j7jbu%6+o@+rwao%q4so&'
)

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

_allowed = os.environ.get('ALLOWED_HOSTS', '')
base_hosts = [h.strip() for h in _allowed.split(',') if h.strip()] or ['localhost', '127.0.0.1']
ALLOWED_HOSTS = base_hosts + ['healthcheck.railway.app', '.railway.app']

_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = (
    [o.strip() for o in _cors.split(',') if o.strip()]
    if _cors else ['http://localhost:4200', 'http://127.0.0.1:4200']
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'core',
    'assets',
    'novedades',
    'personnel.apps.PersonnelConfig',
    'records',
    'hechos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_app_branch = os.environ.get('APP_BRANCH', 'dev').strip().lower() or 'dev'
_db_url = os.environ.get('DATABASE_URL', '').strip()


def _get_database_settings():
    if _db_url:
        return _dj_db_url.parse(_db_url, conn_max_age=600)
    
    volume_path = os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', '').strip()
    db_path = Path(volume_path) / 'db.sqlite3' if volume_path else BASE_DIR / 'db.sqlite3'
    
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_path,
    }


DATABASES = {'default': _get_database_settings()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
_CORE_STATIC = BASE_DIR / 'core' / 'static'
STATICFILES_DIRS = [_CORE_STATIC] if _CORE_STATIC.exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise sirve el build de Angular directamente en / (no bajo /static/)
_ANGULAR_DIST = BASE_DIR.parent / 'frontend' / 'dist' / 'gestor-coc' / 'browser'
WHITENOISE_ROOT = str(_ANGULAR_DIST) if _ANGULAR_DIST.exists() else None

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Upload limits for report generation payloads (JSON + base64 frames)
DATA_UPLOAD_MAX_MEMORY_SIZE = 128 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024

# Video analysis report limits
VIDEO_REPORT_MAX_FRAMES = 30
VIDEO_REPORT_MAX_FRAME_SIZE_BYTES = 8 * 1024 * 1024
VIDEO_REPORT_MAX_TOTAL_BYTES = 80 * 1024 * 1024

# AI text improvement for report narrative fields
AI_TEXT_PROVIDER_ORDER = os.getenv('AI_TEXT_PROVIDER_ORDER', 'gemini,openrouter,groq,ollama')
AI_TEXT_PROVIDER_SELECTION = os.getenv('AI_TEXT_PROVIDER_SELECTION', 'ordered')
AI_TEXT_FALLBACK_MODE = os.getenv('AI_TEXT_FALLBACK_MODE', 'quota_only')
AI_TEXT_TIMEOUT_SECONDS = int(os.getenv('AI_TEXT_TIMEOUT_SECONDS', '45'))

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
AI_TEXT_GEMINI_API_URL = os.getenv(
    'AI_TEXT_GEMINI_API_URL',
    'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
)
AI_TEXT_GEMINI_MODEL = os.getenv('AI_TEXT_GEMINI_MODEL', 'gemini-2.5-flash')

OPEN_ROUTER_API_KEY = os.getenv('OPEN_ROUTER_API_KEY', '')
AI_TEXT_OPENROUTER_API_URL = os.getenv(
    'AI_TEXT_OPENROUTER_API_URL',
    'https://openrouter.ai/api/v1/chat/completions',
)
AI_TEXT_OPENROUTER_MODEL = os.getenv('AI_TEXT_OPENROUTER_MODEL', 'gpt-4o-mini')

GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
AI_TEXT_GROQ_API_URL = os.getenv(
    'AI_TEXT_GROQ_API_URL',
    'https://api.groq.com/openai/v1/chat/completions',
)
AI_TEXT_GROQ_MODEL = os.getenv('AI_TEXT_GROQ_MODEL', 'llama-3.3-70b-versatile')

OLLAMA_API_KEY = os.getenv('OLLAMA_API_KEY', '')
AI_TEXT_OLLAMA_API_URL = os.getenv(
    'AI_TEXT_OLLAMA_API_URL',
    'http://localhost:11434/v1/chat/completions',
)
AI_TEXT_OLLAMA_MODEL = os.getenv('AI_TEXT_OLLAMA_MODEL', 'llama3.2')

# Legacy aliases (backward compatibility)
AI_TEXT_API_URL = os.getenv('AI_TEXT_API_URL', AI_TEXT_OPENROUTER_API_URL)
AI_TEXT_API_KEY = os.getenv('AI_TEXT_API_KEY', OPEN_ROUTER_API_KEY)
AI_TEXT_MODEL = os.getenv('AI_TEXT_MODEL', AI_TEXT_OPENROUTER_MODEL)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Gestor COC API',
    'DESCRIPTION': 'API para la gestión de novedades y equipamiento del COC',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
