# Generated by Django 5.2.9 on 2026-01-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvsystem',
            name='is_coc_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='has_coc',
            field=models.BooleanField(default=False),
        ),
    ]
