# Generated by Django 5.2.9 on 2026-01-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cctvsystem_is_coc_room_organizationalunit_has_coc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.organizationalunit'),
        ),
    ]
