# Generated by Django 6.0.1 on 2026-01-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='guard_group',
            field=models.CharField(blank=True, help_text='Grupo de Guardia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.CharField(blank=True, help_text='Jerarquía', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='unit',
            field=models.CharField(blank=True, help_text='Unidad de Revista', max_length=100, null=True),
        ),
    ]
