# Generated by Django 6.0.1 on 2026-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_person_assigned_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unit',
            field=models.CharField(choices=[('AEP', 'Aeroparque'), ('EZE', 'Ezeiza'), ('FDO', 'San Fernando'), ('BHI', 'Bahía Blanca'), ('MDQ', 'Mar del Plata')], default='AEP', help_text='Unidad de Revista', max_length=5),
        ),
    ]
