# Generated by Django 5.2.11 on 2026-03-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_person_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personal'},
        ),
    ]
