# Generated by Django 5.2.10 on 2026-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Operador COC'), ('SUPERVISOR', 'Fiscalizador CREV'), ('ADMIN', 'Administrador')], default='OPERATOR', max_length=50),
        ),
    ]
