# Generated by Django 6.0.1 on 2026-01-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_unit_remove_system_location_system_unit'),
        ('personnel', '0007_alter_person_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(help_text='Fecha y hora del hecho')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('POLICIAL', 'Policial'), ('OPERATIVO', 'Operativo'), ('INFORMATIVO', 'Informativo'), ('RELEVAMIENTO', 'Relevamiento')], default='OPERATIVO', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos', to='assets.camera')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_hechos', to='personnel.person')),
            ],
            options={
                'verbose_name': 'Hecho',
                'verbose_name_plural': 'Hechos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
