# Generated by Django 6.0.1 on 2026-01-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='coc_intervention',
            field=models.BooleanField(default=False, verbose_name='¿Intervención COC?'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='elements',
            field=models.TextField(blank=True, help_text='Elementos involucrados', null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Hora de finalización', null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='generated_cause',
            field=models.BooleanField(default=False, verbose_name='¿Se generó causa?'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='intervening_groups',
            field=models.CharField(blank=True, help_text='Grupos intervinientes (Policía, SAME, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='¿Se solucionó?'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='resolution_details',
            field=models.TextField(blank=True, help_text='Detalle de la resolución', null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='resolution_time',
            field=models.CharField(blank=True, help_text='Tiempo de resolución (calc)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector o Área donde ocurrió', max_length=100, null=True),
        ),
    ]
