# Generated by Django 6.0.1 on 2026-01-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(default='FALLA_TECNICA', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Critica')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Progreso'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=20)),
                ('reported_by', models.CharField(help_text='User who reported', max_length=100)),
                ('external_ticket_id', models.CharField(blank=True, help_text='Ticket DGT/CCO', max_length=50, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='assets.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
