# Generated by Django 6.0.1 on 2026-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_remove_novedad_external_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='external_ticket_id',
            field=models.CharField(blank=True, help_text='ID del ticket en DGT/CCO', max_length=50, null=True),
        ),
    ]
