export const CATALOG_SEED_DATA = {
    TIPOS_SOLICITUD: [
        "ACTA",
        "CORREO",
        "EMAIL",
        "FORMULARIO",
        "MAIL",
        "MEMORANDO",
        "MEMORANDO S/N SAL/2023",
        "MEMORANDO/GDE",
        "NOTA",
        "NOTA/SOLICITUD",
        "OFICIO",
        "OFICIO MAIL"
    ],
    ORGANISMOS: [
        "AA 2000",
        "AA2000",
        "AFIP",
        "ARCA",
        "CIUDAD",
        "COMPLEJA",
        "COMPLEJA CENTRAL",
        "COMPLEJA ESTE",
        "CONTROL POLICIAL",
        "FISCALIA 29",
        "FISCALIA NACIONAL EN LO CRIMINAL Y CORRECCIONAL NRO 40",
        "FISCALIA NRO.02",
        "FISCALIA NRO.09",
        "FISFED NRO.02",
        "GNA",
        "INTERPOL",
        "JUDICIALES",
        "MINISTERIO DE RELACIONES EXTERIORES",
        "PBA",
        "PFA",
        "PNA",
        "POLICIA DE LA CIUDAD",
        "PROCUNAR-PFA",
        "PSA",
        "SUMARIOS",
        "UOA",
        "UOCN Y DC 1 DEL ESTE",
        "UOCN Y DC1"
    ],
    TIPOS_DELITO: [
        "ABUSO",
        "ACOSO",
        "AMENAZAS",
        "AMPLIACION",
        "APROPIACION",
        "APROPIACION INDEBIDA",
        "ATENTADO",
        "AV DE HECHO",
        "AV DE ILICITO",
        "AVERIGUACION DE ILICITO",
        "CONTRABANDO",
        "CONTRABANDO DE DIVISAS",
        "DAÑO",
        "DAÑOS",
        "DELITO",
        "DENUNCIA",
        "DESESTIMADO",
        "ESTAFA",
        "ESTUPEFACIENTE",
        "EXTRAVIO",
        "FALTANTE",
        "FALTANTE DE EQUIPAJE",
        "HOSTIGAMIENTO",
        "HURTO",
        "HURTO DE EQUIPAJE",
        "HURTO DE MOCHILA",
        "INCENDIO",
        "INF LEY 22415",
        "INF LEY 23737",
        "INFRACCION",
        "LESIONES",
        "MALTRATO",
        "PARADERO",
        "PEDIDO AVSEC",
        "PORTACION",
        "RESISTENCIA A LA AUTORIDAD",
        "ROBO",
        "SEGUIMIENTO",
        "TENTATIVA DE HURTO",
        "TENTATIVA DE ROBO",
        "TRATA"
    ],
    // Muestreo de las unidades más relevantes o limpias (hay 225 en total)
    // Esta lista se puede expandir según necesidad.
    UNIDADES_PRINCIPALES: [
        "AA 2000",
        "AFIP",
        "ANAC",
        "ASUNTOS INTERNOS",
        "AVSEC",
        "BAHIA BLANCA",
        "BARILOCHE",
        "CALAFATE",
        "CATAMARCA",
        "CEAC",
        "COC EZEIZA",
        "COMODORO RIVADAVIA",
        "COMPLEJA CENTRAL",
        "CONTROL POLICIAL",
        "CORDOBA",
        "CORRIENTES",
        "DGA",
        "DGT",
        "DOPA",
        "DROPA",
        "DSA/PSA",
        "DSI/PSA",
        "EZEIZA",
        "FORMOSA",
        "GNA",
        "IGUAZU",
        "INTELIGENCIA CRIMINAL",
        "INTERPOL",
        "JUJUY",
        "JUZGADO FEDERAL",
        "MAR DEL PLATA",
        "MENDOZA",
        "METROPOLITANA",
        "MINISTERIO DE SEGURIDAD",
        "NEUQUEN",
        "ODT",
        "PBA",
        "PFA",
        "PNA",
        "POLICIA DE LA CIUDAD",
        "POSADAS",
        "PROCUNAR",
        "PSA",
        "PUERTO MADRYN",
        "RIO GALLEGOS",
        "RIO GRANDE",
        "ROSARIO",
        "SALTA",
        "SAN FERNANDO",
        "SAN JUAN",
        "SAN LUIS",
        "SENASA",
        "TUCUMAN",
        "UOA",
        "USHUAIA",
        "YPF"
    ]
};
