# Generated by Django 6.0.1 on 2026-01-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_camera_id_alter_system_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='system',
        ),
        migrations.RemoveField(
            model_name='system',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('NVR', 'NVR (Grabador)'), ('CCTV', 'Sistema CCTV Completo')], default='CCTV', max_length=10),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='assets.system')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='assets.server'),
        ),
    ]
