# Generated by Django 5.2.11 on 2026-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_unit_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'En Linea'), ('OFFLINE', 'Fuera de Linea'), ('MAINTENANCE', 'Mantenimiento')], db_index=True, default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cameramangear',
            name='assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Nombre del camarógrafo responsable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cameramangear',
            name='name',
            field=models.CharField(db_index=True, help_text='e.g., Chaleco, Radio, Batería', max_length=100),
        ),
        migrations.AlterField(
            model_name='cameramangear',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(db_index=True, help_text='e.g., SITE-01-NVR', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(db_index=True, help_text='e.g., AEP, EZE', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
