# Generated by Django 5.2.10 on 2026-03-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_unit_geo_fields'),
        ('personnel', '0009_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramangear',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Nombre libre (legado)', max_length=100),
        ),
        migrations.RunSQL(
            # Copia texto libre a assigned_to_name, luego limpia la columna para poder cambiar el tipo a FK
            sql="UPDATE assets_cameramangear SET assigned_to_name = assigned_to WHERE assigned_to IS NOT NULL AND assigned_to != ''; UPDATE assets_cameramangear SET assigned_to = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='cameramangear',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gear', to='personnel.person'),
        ),
    ]
