# Generated by Django 5.2.11 on 2026-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='external_ticket_id',
        ),
        migrations.AddField(
            model_name='novedad',
            name='coc_ticket_number',
            field=models.CharField(blank=True, help_text='Número de ticket generado por la sala COC/DGT', max_length=100, null=True, verbose_name='Número de Ticket COC'),
        ),
    ]
