# Generated by Django 5.2.11 on 2026-03-06 18:20
# Rewritten to use SeparateDatabaseAndState: reported_by_id column already
# existed in the DB; only Django state needs updating.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0006_alter_novedad_incident_type_alter_novedad_severity_and_more'),
        ('personnel', '0010_alter_person_guard_group_alter_person_rank_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='novedad',
                    name='reported_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_reportadas', to='personnel.person'),
                ),
            ],
        ),
    ]
