# Generated by Django 5.2 on 2026-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_alter_novedad_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
