# Generated by Django 5.2 on 2026-04-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Fecha y hora del hecho')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('POLICIAL', 'Policial'), ('OPERATIVO', 'Operativo'), ('INFORMATIVO', 'Informativo'), ('RELEVAMIENTO', 'Relevamiento')], default='OPERATIVO', max_length=20)),
                ('sector', models.CharField(blank=True, help_text='Sector o Área donde ocurrió', max_length=100, null=True)),
                ('elements', models.TextField(blank=True, help_text='Elementos involucrados', null=True)),
                ('intervening_groups', models.CharField(blank=True, help_text='Grupos intervinientes (Policía, SAME, etc.)', max_length=200, null=True)),
                ('is_solved', models.BooleanField(default=False, verbose_name='¿Se solucionó?')),
                ('coc_intervention', models.BooleanField(default=False, verbose_name='¿Intervención COC?')),
                ('generated_cause', models.BooleanField(default=False, verbose_name='¿Se generó causa?')),
                ('end_time', models.DateTimeField(blank=True, help_text='Hora de finalización', null=True)),
                ('resolution_time', models.CharField(blank=True, help_text='Tiempo de resolución (calc)', max_length=100, null=True)),
                ('resolution_details', models.TextField(blank=True, help_text='Detalle de la resolución', null=True)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos', to='assets.camera')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_hechos', to='personnel.person')),
            ],
            options={
                'verbose_name': 'Hecho',
                'verbose_name_plural': 'Hechos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
