# Generated by Django 5.2 on 2026-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0002_hecho_coc_intervention_hecho_elements_hecho_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora del hecho'),
        ),
    ]
