# Generated by Django 5.2.9 on 2026-01-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('server_name', models.CharField(blank=True, max_length=120)),
                ('device_name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('logical_id', models.CharField(blank=True, max_length=120)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('camera_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=120)),
                ('firmware_required', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('connected', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('error_indicators', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('bitrate_kbps', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('frame_rate', models.CharField(blank=True, max_length=50)),
                ('encryption', models.CharField(blank=True, max_length=80)),
                ('retention', models.CharField(blank=True, max_length=120)),
                ('appearance_search', models.CharField(blank=True, max_length=120)),
                ('face_recognition', models.CharField(blank=True, max_length=120)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['server_name', 'device_name'],
                'indexes': [models.Index(fields=['server_name', 'device_name'], name='inventory_c_server__853586_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('service_date_text', models.CharField(blank=True, max_length=120)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('service_order', models.CharField(blank=True, max_length=120)),
                ('deployment', models.CharField(blank=True, max_length=200)),
                ('allanamiento', models.CharField(blank=True, max_length=200)),
                ('police_procedure', models.CharField(blank=True, max_length=200)),
                ('other_notes', models.CharField(blank=True, max_length=200)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_name'], name='inventory_e_source__910b06_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('brand_model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=180)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('unit_status', models.CharField(blank=True, max_length=80)),
                ('delivered', models.CharField(blank=True, max_length=50)),
                ('observations', models.CharField(blank=True, max_length=255)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.equipmentregister')),
            ],
        ),
    ]
