# Generated by Django 6.0.1 on 2026-01-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., SITE-01-NVR', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'En Linea'), ('OFFLINE', 'Fuera de Linea'), ('MAINTENANCE', 'Mantenimiento')], default='ONLINE', max_length=20)),
                ('resolution', models.CharField(default='1080p', max_length=20)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='assets.system')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
