# Generated by Django 5.2.9 on 2026-01-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], db_index=True, default='ENTRADA', max_length=20)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(db_index=True, max_length=120, unique=True)),
                ('sender', models.CharField(max_length=150)),
                ('recipient', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO', 'EN_PROCESO'), ('ARCHIVADO', 'ARCHIVADO'), ('FINALIZADO', 'FINALIZADO')], db_index=True, default='PENDIENTE', max_length=20)),
                ('priority', models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], default='MEDIA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='FilmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_asunto', models.CharField(max_length=120)),
                ('nro_orden', models.CharField(blank=True, max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('nro_solicitud', models.CharField(blank=True, max_length=120)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
                ('causa_judicial', models.CharField(blank=True, max_length=200)),
                ('caratula', models.CharField(blank=True, max_length=200)),
                ('fecha_hecho', models.DateField(blank=True, null=True)),
                ('recepcionado_por', models.CharField(blank=True, max_length=150)),
                ('confeccionado_por', models.CharField(blank=True, max_length=150)),
                ('detalle', models.TextField(blank=True)),
                ('nro_dvd', models.CharField(blank=True, max_length=120)),
                ('nro_informe', models.CharField(blank=True, max_length=120)),
                ('ifgra', models.CharField(blank=True, max_length=120)),
                ('nro_expediente', models.CharField(blank=True, max_length=120)),
                ('acta_entrega', models.CharField(blank=True, max_length=120)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('retirado_por', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], db_index=True, default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_records_created', to=settings.AUTH_USER_MODEL)),
                ('org_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_records', to='core.cctvsystem')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_records', to='core.organizationalunit')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_record_organizations', to='core.catalogitem')),
                ('tipo_delito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_record_crime_types', to='core.catalogitem')),
                ('tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_record_request_types', to='core.catalogitem')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_record_units', to='core.catalogitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference_number'], name='documents_d_referen_2dd071_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['priority'], name='documents_d_priorit_312b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['estado'], name='documents_f_estado_93f24b_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['fecha_ingreso'], name='documents_f_fecha_i_923548_idx'),
        ),
    ]
