# Generated by Django 5.2.10 on 2026-03-05 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo numeros (entre 7 y 10 digitos).', regex='^\\d{7,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('function', models.CharField(help_text='Funcion que cumple', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal externo',
                'verbose_name_plural': 'Personal externo',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(help_text='Legajo (6 digitos)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El legajo debe contener exactamente 6 digitos.', regex='^\\d{6}$')])),
                ('role', models.CharField(choices=[('OPERADOR', 'Operador COC'), ('SUPERVISOR', 'Fiscalizador CREV'), ('ADMIN', 'Administrador')], default='OPERADOR', max_length=50)),
                ('rank', models.CharField(choices=[('JEFE', 'Jefe'), ('OFICIAL_AYUDANTE_PRINCIPAL', 'Oficial Ayudante Principal'), ('OFICIAL_PRINCIPAL', 'Oficial Principal'), ('OFICIAL', 'Oficial'), ('MAYOR', 'Mayor'), ('OFICIAL_JEFE', 'Oficial Jefe'), ('SUBINSPECTOR', 'Subinspector'), ('INSPECTOR', 'Inspector'), ('COMISIONADO_MAYOR', 'Comisionado Mayor'), ('COMISIONADO_GENERAL', 'Comisionado General'), ('CIVIL', 'Civil')], default='CIVIL', help_text='Jerarquia', max_length=40)),
                ('guard_group', models.CharField(blank=True, help_text='Grupo de guardia', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_systems', models.ManyToManyField(blank=True, help_text='Sistemas asignados', related_name='personnel', to='assets.system')),
                ('unit', models.ForeignKey(blank=True, help_text='Unidad de revista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='assets.unit')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
