# Generated by Django 5.2.11 on 2026-03-20 23:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo numeros (entre 7 y 10 digitos).', regex='^\\d{7,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('function', models.CharField(help_text='Funcion que cumple', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal externo',
                'verbose_name_plural': 'Personal externo',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(help_text='Legajo (6 digitos)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El legajo debe contener exactamente 6 digitos.', regex='^\\d{6}$')])),
                ('role', models.CharField(choices=[('OPERADOR', 'Operador'), ('COORDINADOR_COC', 'Coordinador COC'), ('CREV', 'CREV'), ('COORDINADOR_CREV', 'Coordinador CREV'), ('ADMIN', 'Administrador')], default='OPERADOR', max_length=50)),
                ('rank', models.CharField(choices=[('OFICIAL_AYUDANTE', 'Of. Ayte. '), ('OFICIAL_PRINCIPAL', 'Of. Ppal.'), ('OFICIAL_MAYOR', 'Of. Mayor'), ('OFICIAL_JEFE', 'Of. Jefe'), ('SUBINSPECTOR', 'Subinspector'), ('INSPECTOR', 'Inspector'), ('COMISIONADO_MAYOR', 'Com. Mayor'), ('COMISIONADO_GENERAL', 'Com. Gral.'), ('CIVIL', 'Civil')], default='CIVIL', help_text='Jerarquia', max_length=40)),
                ('guard_group', models.CharField(blank=True, help_text='Grupo de guardia', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_systems', models.ManyToManyField(blank=True, help_text='Sistemas asignados', related_name='personnel', to='assets.system')),
                ('unit', models.ForeignKey(blank=True, help_text='Unidad de revista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='assets.unit')),
                ('user', models.OneToOneField(blank=True, help_text='Cuenta de sistema asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='UserAccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de cuenta',
                'verbose_name_plural': 'Perfiles de cuenta',
            },
        ),
    ]
