# Generated by Django 5.2.11 on 2026-03-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_camera_server_cameramangear_assigned_to_name_and_more'),
        ('personnel', '0009_alter_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='guard_group',
            field=models.CharField(blank=True, help_text='Grupo de guardia', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.CharField(choices=[('JEFE', 'Jefe'), ('OFICIAL_AYUDANTE_PRINCIPAL', 'Oficial Ayudante Principal'), ('OFICIAL_PRINCIPAL', 'Oficial Principal'), ('OFICIAL', 'Oficial'), ('MAYOR', 'Mayor'), ('OFICIAL_JEFE', 'Oficial Jefe'), ('SUBINSPECTOR', 'Subinspector'), ('INSPECTOR', 'Inspector'), ('COMISIONADO_MAYOR', 'Comisionado Mayor'), ('COMISIONADO_GENERAL', 'Comisionado General'), ('CIVIL', 'Civil')], default='CIVIL', help_text='Jerarquia', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OP_EXTRACTION', 'Operador Basico (Extraccion/Visualizacion)'), ('OP_CONTROL', 'Operador de Camaras (Fijas/Domos/PTZ)'), ('OP_VIEWER', 'Solo Visualizacion')], default='OP_VIEWER', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de revista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='assets.unit'),
        ),
    ]
