# Generated by Django 5.2.12 on 2026-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_person_guard_group_alter_person_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.CharField(choices=[('OFICIAL_AYUDANTE', 'Of. Ayte. '), ('OFICIAL_PRINCIPAL', 'Of. Ppal.'), ('OFICIAL_MAYOR', 'Of. Mayor'), ('OFICIAL_JEFE', 'Of. Jefe'), ('SUBINSPECTOR', 'Subinspector'), ('INSPECTOR', 'Inspector'), ('COMISIONADO_MAYOR', 'Com. Mayor'), ('COMISIONADO_GENERAL', 'Com. Gral.'), ('CIVIL', 'Civil')], default='CIVIL', help_text='Jerarquia', max_length=40),
        ),
    ]
