# Generated by Django 5.2.12 on 2026-03-10 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_person_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo numeros (entre 7 y 10 digitos).', regex='^\\d{7,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('function', models.CharField(help_text='Funcion que cumple', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal externo',
                'verbose_name_plural': 'Personal externo',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='badge_number',
            field=models.CharField(help_text='Legajo (6 digitos)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El legajo debe contener exactamente 6 digitos.', regex='^\\d{6}$')]),
        ),
    ]
