# Generated by Django 5.2 on 2026-03-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_useraccountprofile_person_user_and_role_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
