# Generated by Django 6.0.1 on 2026-01-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_camera_id_alter_system_id'),
        ('personnel', '0003_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('record_type', models.CharField(choices=[('VD', 'VD - Video'), ('IM', 'Imagen'), ('OT', 'Otro')], default='VD', max_length=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_hash', models.CharField(blank=True, help_text='SHA-256 integrity hash', max_length=64, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='assets.camera')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='personnel.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('records', models.ManyToManyField(related_name='catalogs', to='records.filmrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
