# Generated by Django 5.2.9 on 2026-01-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.PositiveIntegerField(db_index=True)),
                ('fecha_intervencion', models.DateTimeField(db_index=True)),
                ('novedad', models.CharField(blank=True, max_length=200)),
                ('quien_detecta', models.CharField(choices=[('Guardia de Prevencion', 'Guardia de Prevencion'), ('Centro Monitoreo', 'Centro Monitoreo')], max_length=50)),
                ('elementos', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('solucionado_coc', models.BooleanField(default=False)),
                ('genero_causa', models.BooleanField(default=False)),
                ('hs_resolucion', models.CharField(blank=True, max_length=120)),
                ('detalle_cierre', models.TextField(blank=True)),
                ('sugerencia', models.CharField(blank=True, max_length=200)),
                ('falencia', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_intervencion'],
                'indexes': [models.Index(fields=['fecha_intervencion'], name='operations__fecha_i_0e2490_idx'), models.Index(fields=['nro_orden'], name='operations__nro_ord_afe6dc_idx')],
            },
        ),
    ]
