# Generated by Django 5.2.9 on 2026-01-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hecho',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_resueltos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hecho',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], db_index=True, default='Abierto', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hecho',
            index=models.Index(fields=['status'], name='operations__status_9b8a18_idx'),
        ),
    ]
