# Generated by Django 5.2.9 on 2026-01-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_hecho_resolved_at_hecho_resolved_by_hecho_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='status',
            field=models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], db_index=True, default='Abierto', max_length=20),
        ),
    ]
