# Generated by Django 5.2.9 on 2026-01-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('operations', '0003_alter_hecho_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos', to='inventory.camera'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='cctv_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos', to='core.cctvsystem'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='resolved_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_resueltos', to='core.organizationalgroup'),
        ),
    ]
