# Generated by Django 6.0.1 on 2026-01-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
