# Generated by Django 6.0.1 on 2026-01-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_cameramangear'),
        ('novedades', '0003_alter_novedad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='external_ticket_id',
        ),
        migrations.AddField(
            model_name='novedad',
            name='cameraman_gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='assets.cameramangear'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='assets.server'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='assets.system'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='assets.camera'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='incident_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='reported_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10),
        ),
    ]
