# Generated by Django 5.2.11 on 2026-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_novedad_external_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='incident_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Progreso'), ('CLOSED', 'Cerrada')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
