# Generated by Django 5.2.10 on 2026-03-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Necesario para ALTER TABLE con cambio de tipo en PostgreSQL

    dependencies = [
        ('novedades', '0006_alter_novedad_incident_type_alter_novedad_severity_and_more'),
        ('personnel', '0009_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='reporter_name',
            field=models.CharField(blank=True, help_text='Nombre libre (legado)', max_length=100),
        ),
        migrations.RunSQL(
            # 1. Suelta NOT NULL, 2. copia texto a reporter_name, 3. limpia la columna original
            sql="""
                ALTER TABLE novedades_novedad ALTER COLUMN reported_by DROP NOT NULL;
                UPDATE novedades_novedad SET reporter_name = reported_by WHERE reported_by IS NOT NULL AND reported_by != '';
                UPDATE novedades_novedad SET reported_by = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='novedad',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_reportadas', to='personnel.person'),
        ),
    ]
