# Generated by Django 6.0.1 on 2026-01-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_camera_system_remove_system_ip_address_and_more'),
        ('personnel', '0004_person_guard_group_person_rank_person_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='assigned_systems',
            field=models.ManyToManyField(blank=True, help_text='Sistemas asignados', related_name='personnel', to='assets.system'),
        ),
    ]
