# Generated by Django 6.0.1 on 2026-01-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_unit_remove_system_location_system_unit'),
        ('personnel', '0006_alter_person_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de Revista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='assets.unit'),
        ),
    ]
