# Generated by Django 5.2 on 2026-04-08 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('role', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('method', models.CharField(blank=True, db_index=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=200)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('target_app', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
