# Generated by Django 6.0.1 on 2026-01-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_unit_remove_system_location_system_unit'),
        ('personnel', '0007_alter_person_unit'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmrecord',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Registro Fílmico', 'verbose_name_plural': 'Registros Fílmicos'},
        ),
        migrations.RemoveField(
            model_name='filmrecord',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='filmrecord',
            name='verification_hash',
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='backup_path',
            field=models.CharField(blank=True, help_text='Ubicación física o lógica del backup', max_length=500, null=True, verbose_name='Ruta del Backup'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='case_title',
            field=models.TextField(blank=True, help_text='Carátula de la causa', null=True, verbose_name='Carátula'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='crime_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Delito'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='delivery_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Entrega'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='entry_date',
            field=models.DateField(blank=True, help_text='Fecha de ingreso de la solicitud', null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash para verificación de integridad', max_length=64, null=True, verbose_name='Hash del Archivo'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Tamaño en bytes', null=True, verbose_name='Tamaño del Archivo'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='has_backup',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Backup?'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='incident_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Hecho'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='intervening_department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependencia Interviniente'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='False si ya fue verificado por CREV', verbose_name='¿Es Editable?'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='is_integrity_verified',
            field=models.BooleanField(default=False, help_text='Verificación técnica automática del hash', verbose_name='¿Integridad Verificada?'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='issue_number',
            field=models.CharField(blank=True, help_text='Número de asunto administrativo', max_length=50, null=True, verbose_name='Nro Asunto'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='judicial_case_number',
            field=models.CharField(blank=True, db_index=True, help_text='Número de causa o prevención sumaria', max_length=100, null=True, verbose_name='Nº Causa Judicial'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='order_number',
            field=models.IntegerField(blank=True, help_text='Número de orden secuencial', null=True, verbose_name='Nº Orden'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_records', to='personnel.person', verbose_name='Recepcionado por'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='request_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Solicitud'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='request_type',
            field=models.CharField(blank=True, choices=[('OFICIO', 'Oficio'), ('NOTA', 'Nota'), ('EXHORTO', 'Exhorto'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo Solicitud'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='requester',
            field=models.CharField(blank=True, help_text='Juzgado, Fiscalía u organismo solicitante', max_length=200, null=True, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación CREV'),
        ),
        migrations.AddField(
            model_name='filmrecord',
            name='verified_by_crev',
            field=models.ForeignKey(blank=True, help_text='Fiscalizador CREV que certificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_records', to='personnel.person', verbose_name='Verificado por CREV'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='assets.camera', verbose_name='Cámara'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='end_time',
            field=models.DateTimeField(verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_records', to='personnel.person', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='record_type',
            field=models.CharField(choices=[('VD', 'VD - Video'), ('IM', 'Imagen'), ('OT', 'Otro')], default='VD', max_length=2, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='start_time',
            field=models.DateTimeField(verbose_name='Hora Inicio'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['judicial_case_number'], name='records_fil_judicia_de6410_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['issue_number'], name='records_fil_issue_n_b8c176_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['entry_date'], name='records_fil_entry_d_7158a8_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['delivery_status'], name='records_fil_deliver_b761fe_idx'),
        ),
        migrations.AddIndex(
            model_name='filmrecord',
            index=models.Index(fields=['file_hash'], name='records_fil_file_ha_bb8ee6_idx'),
        ),
    ]
