# Generated by Django 5.2.11 on 2026-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_filmrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(choices=[('improve_text', 'Mejora de texto'), ('video_report', 'Generación de informe')], default='improve_text', max_length=30)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de uso de IA',
                'verbose_name_plural': 'Registros de uso de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
