# Generated by Django 5.2.11 on 2026-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_add_hash_algorithm_and_ollama_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filmrecord',
            name='delivery_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('DERIVADO', 'Derivado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Entrega'),
        ),
    ]
