# Generated by Django 6.0.1 on 2026-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_camera_system_remove_system_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameramanGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Chaleco, Radio, Batería', max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Nombre del camarógrafo responsable', max_length=100, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'Nuevo'), ('GOOD', 'Bueno'), ('FAIR', 'Regular'), ('POOR', 'Malo'), ('BROKEN', 'Roto')], default='GOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
