# Generated by Django 6.0.1 on 2026-01-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_unit_remove_system_location_system_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Entidad Superior (e.g., CREV)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='assets.unit'),
        ),
    ]
