# Generated by Django 5.2.11 on 2026-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_unit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='airport',
            field=models.CharField(blank=True, help_text='Aeropuerto', max_length=100, null=True),
        ),
    ]
