# Generated by Django 5.2.11 on 2026-03-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('assets', '0009_alter_camera_name_alter_camera_status_and_more'),
    ]

    operations = [
    ]
